config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#custom'

  devise_for :users
  root "players#index"

  get "/search" => "players#search"
  get "/pages/about" => "pages#about"
  get "/teams/schedule" => "teams#schedule"
  get "/players/compare" => "players#compare"

  resources :players, param: :player_id do
    collection do
      post :conditions
    end
  end

  # resources :posts

  # API routes
  namespace :api do
    namespace :v1 do
      get "leagues/index", to: "leagues#index"
      get "leagues/roster", to: "leagues#roster"
      get "players/value/:player_id", to: "players#value"
      get "players/log/:player_id", to: "players#log"
      get "players/info/:player_id", to: "players#info"
      get "players/list", to: "players#list"
      get "players/score/:player_id", to: "players#score"
      get "teams/schedule", to: "teams#schedule"
    end
  end

  resources :leagues
end

app/models/player.rb
class Player < ApplicationRecord

  belongs_to :team, optional: true
  has_one :value
  has_one :stat
  has_many :game_log

  # attr_accessor :rank_value
  #
  # def initialize
  #   @rank_value = 0
  # end

end

app/controllers/api/v1/players_controller.rb
class Api::V1::PlayersController < ApplicationController

  def list

    players = []
    gamelog = GameLog.select("player_id").where("min <> '' AND min <> '0'").group("player_id").includes(:player)
    gamelog.map do |g|
      players << {
        id: g.player_id,
        name: g.player.name
      }
    end

    render json: {
      playerList: players.sort_by { |hsh| hsh[:name] }
    }
  end

  # send query include player_id to search player
  def info
    player = GameLog.where("player_id = ?", params[:player_id])
    league = GameLog.all
    name = player[0].player.name
    team_name = player[0].player.team.full_name
    team_tricode = player[0].player.team.tricode
    pos = player[0].player.pos

    points = player.average(:points).round(1)
    league_points = league.average(:points).round(1)

    tpm = player.average(:tpm).round(1)
    league_tpm = league.average(:tpm).round(1)

    tot_reb = player.average(:tot_reb).round(1)
    league_tot_reb = league.average(:tot_reb).round(1)

    assists = player.average(:assists).round(1)
    league_assists = league.average(:assists).round(1)

    steals = player.average(:steals).round(1)
    league_steals = league.average(:steals).round(1)

    blocks = player.average(:blocks).round(1)
    league_blocks = league.average(:blocks).round(1)

    if player
      render json: {
        playerInfo: {
          name: name,
          team_name: team_name,
          team_tricode: team_tricode,
          pos: pos,
          points: points,
          tpm: tpm,
          tot_reb: tot_reb,
          assists: assists,
          steals: steals,
          blocks: blocks
        },
        leagueInfo: {
          points: league_points,
          tpm: league_tpm,
          tot_reb: league_tot_reb,
          assists: league_assists,
          steals: league_steals,
          blocks: league_blocks
        }
      }
    else
      render json: player.errors
    end
  end

  # get player total item score
  def score
    playerValue = ZScore.player_value_by_game(82, params[:player_id])
    render json: {
      playerValue: playerValue
    }
  end

  # get player by week
  def value
    player = Player.find(params[:player_id])

    if player
      player_data = []
      # by week
      # 賽季開始日期
      game_start = Date.parse("2019-10-22")
      # 賽季結束日期
      game_end = Date.parse("2020-04-15")
      # 目前週數
      current_week = Date.parse("2019-10-22")
      week = 0

      conditions = ["points", "three_point", "assists", "steals", "blocks", "field_goal", "free_throw", "off_reb", "def_reb", "turnovers", "p_fouls"]

      while current_week < DateTime.now.utc.to_date && current_week <= game_end do
        week_start = current_week.strftime("%F")
        week_end = (current_week + 7).strftime("%F")
        player_data << {
          "week": week + 1,
          "name": player.name,
          "value": get_rank_value(ZScore.player_value_by_week(82, week_start, week_end, params[:player_id]).to_a[0], conditions),
          "league_value": get_rank_value(ZScore.league_value_by_week(82, week_start, week_end).to_a[0], conditions)
        }

        current_week += 7
        week += 1
      end

      if player_data
        render json: { playerWeekValue: player_data }
      else
        render json: player_data.errors
      end
    else
      render json: player.errors
    end
  end

  def log
    game_num = params[:game] || 10
    player_game_log = GameLog.where("player_id = ?", params[:player_id]).order(game_time: :desc).limit(game_num)
    if player_game_log
      render json: { game_log: player_game_log }
    else
      render json: player_game_log.errors
    end
  end

  private
  def get_rank_value(value, conditions)
    rank_value = 0

    unless value.nil?
        conditions.each do |condition|

        case condition
        when "points"
          rank_value += value["points_value"].to_f
        when "three_point"
          rank_value += value["three_point_value"].to_f
        when "assists"
          rank_value += value["assists_value"].to_f
        when "steals"
          rank_value += value["steals_value"].to_f
        when "blocks"
          rank_value += value["blocks_value"].to_f
        when "field_goal"
          rank_value += value["field_goal_value"].to_f
        when "free_throw"
          rank_value += value["free_throw_value"].to_f
        when "off_reb"
          rank_value += value["off_reb_value"].to_f
        when "def_reb"
          rank_value += value["def_reb_value"].to_f
        when "turnovers"
          rank_value += value["turnovers_value"].to_f
        when "p_fouls"
          rank_value += value["p_fouls_value"].to_f
        end
      end
    end

    return rank_value
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @user_filter = { "conditions" => ["points_value", "three_point_value", "assists_value", "steals_value", "blocks_value", "field_goal_value", "free_throw_value", "off_reb_value", "def_reb_value", "turnovers_value", "p_fouls_value"], "game" => 82 }

    # rank value 條件
    if session[:search_conditions].nil?
      session[:search_conditions] = @user_filter
    else
      @user_filter = session[:search_conditions]
    end

    @players = ZScore.player_value_by_game(@user_filter["game"]).to_a

    # # 計算player value
    @players.each do |p|
      p["rank_value"] = get_rank_value(p, @user_filter["conditions"])
    end
  end

  def conditions
    session[:search_conditions] = nil
    session[:search_conditions] = {"conditions" => params[:conditions], "game" => params[:game]}
    redirect_to root_path
  end

  def show
    @player = GameLog.where("player_id = ?", params[:player_id])
    # @player = []
    # # by 場次
    # game = [7, 14, 30]
    # 3.times { |index| @player << ZScore.player_value_by_game(game[index], params[:player_id]).to_a[0] }
  end

  def compare

  end

  def search
    if params[:search].blank?
      redirect_to root_path
    else
      player = Player.find_by(name: params[:search])
      redirect_to player_path(player.id)
    end
  end

  private
  def get_rank_value(value, conditions)
    rank_value = 0

    conditions.each do |condition|
      rank_value += value[condition].to_f
    end

    return rank_value
  end
end

app/views/players/compare.html.erb
<% content_for :head do %>
  <%= javascript_pack_tag 'compare' %>
<% end %>
<div id="compare_app" class="container">
</div>

app/views/players/index.html.erb
<div class="container">
  <div class="row">
    <%= form_tag(conditions_players_path, method: "post") do %>
      <div class="form-row">
        比項
      </div>
      <div class="form-row">
        <div class="form-check form-check-inline">
        <%= check_box_tag("conditions[]", "points_value", @user_filter["conditions"].include?("points_value"), class: "form-check-input") %>
        <%= label_tag("points_value", "得分", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "three_point_value", @user_filter["conditions"].include?("three_point_value"), class: "form-check-input") %>
          <%= label_tag("three_point_value", "三分", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "assists_value", @user_filter["conditions"].include?("assists_value"), class: "form-check-input") %>
          <%= label_tag("assists_value", "助攻", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "steals_value", @user_filter["conditions"].include?("steals_value"), class: "form-check-input") %>
          <%= label_tag("steals_value", "抄截", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "blocks_value", @user_filter["conditions"].include?("blocks_value"), class: "form-check-input") %>
          <%= label_tag("blocks_value", "火鍋", class: "form-check-label") %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "field_goal_value", @user_filter["conditions"].include?("field_goal_value"), class: "form-check-input") %>
          <%= label_tag("field_goal_value", "命中率", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "free_throw_value", @user_filter["conditions"].include?("free_throw_value"), class: "form-check-input") %>
          <%= label_tag("free_throw_value", "罰球率", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "tot_reb_value", @user_filter["conditions"].include?("tot_reb_value"), class: "form-check-input") %>
          <%= label_tag("tot_reb_value", "籃板", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "off_reb_value", @user_filter["conditions"].include?("off_reb_value"), class: "form-check-input") %>
          <%= label_tag("off_reb_value", "進攻籃板", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "def_reb_value", @user_filter["conditions"].include?("def_reb_value"), class: "form-check-input") %>
          <%= label_tag("def_reb_value", "防守籃板", class: "form-check-label") %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "turnovers_value", @user_filter["conditions"].include?("turnovers_value"), class: "form-check-input") %>
          <%= label_tag("turnovers_value", "失誤", class: "form-check-label") %>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag("conditions[]", "p_fouls_value", @user_filter["conditions"].include?("p_fouls_value"), class: "form-check-input") %>
          <%= label_tag("p_fouls_value", "犯規", class: "form-check-label") %>
        </div>
      </div>
      <div class="form-row">
        <%= select_tag("game", options_for_select([["2020球季", 82], ["過去7場",7], ["過去14場",14], ["過去30場",30]])) %>
        <%= submit_tag "確定" %>
      </div>
    <% end %>
  </div>
  <main role="main" class="container mt-3">
    <div class="col custom-table-width">
      <table class="table table-hover table-sm player-table">
        <thead class="thead-dark">
          <tr class="pd-1">
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Team</th>
            <th scope="col">Pos</th>
            <th scope="col">g</th>
            <th scope="col">m/g</th>
            <th scope="col">pV</th>
            <th scope="col">3V</th>
            <th scope="col">aV</th>
            <th scope="col">sV</th>
            <th scope="col">bV</th>
            <th scope="col">fg%V</th>
            <th scope="col">ft%V</th>
            <th scope="col">orV</th>
            <th scope="col">drV</th>
            <th scope="col">rebV</th>
            <th scope="col">pfV</th>
            <th scope="col">toV</th>
            <th scope="col">p/g</th>
            <th scope="col">3/g</th>
            <th scope="col">a/g</th>
            <th scope="col">s/g</th>
            <th scope="col">b/g</th>
            <th scope="col">fg%</th>
            <th scope="col">ft%</th>
            <th scope="col">or/g</th>
            <th scope="col">dr/g</th>
            <th scope="col">reb/g</th>
            <th scope="col">pf/g</th>
            <th scope="col">to/g</th>
            <th scope="col">v</th>
          </tr>
        </thead>
        <tbody>
          <% @players.sort_by{|p| p["rank_value"]}.reverse.take(350).each.with_index do |player, index| %>
            <tr class="pd-1">
              <th scope="row"><%= index + 1  %></th>
              <td><%= link_to player["name"], player_path(player["player_id"]) %></td>
              <td><%= player["tricode"] %></td>
              <td><%= player["pos"] %></td>
              <td><%= player["g"] %></td>
              <td><%= Time.parse(player["min"]).min %>:<%= Time.parse(player["min"]).sec %></td>
              <td class="pa-value"><%= player["points_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["three_point_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["assists_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["steals_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["blocks_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["field_goal_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["free_throw_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["off_reb_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["def_reb_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["tot_reb_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["p_fouls_value"].to_f.round(1) %></td>
              <td class="pa-value"><%= player["turnovers_value"].to_f.round(1) %></td>
              <td><%= player["points_per_game"].to_f.round(1) %></td>
              <td><%= player["tpm"].to_f.round(1) %></td>
              <td><%= player["assists_per_game"].to_f.round(1) %></td>
              <td><%= player["steals_per_game"].to_f.round(1) %></td>
              <td><%= player["blocks_per_game"].to_f.round(1) %></td>
              <td><%= player["fgp"].to_f.round(2) %></td>
              <td><%= player["ftp"].to_f.round(2) %></td>
              <td><%= player["off_reb_per_game"].to_f.round(1) %></td>
              <td><%= player["def_reb_per_game"].to_f.round(1) %></td>
              <td><%= player["tot_reb_per_game"].to_f.round(1) %></td>
              <td><%= player["p_fouls_per_game"].to_f.round(1) %></td>
              <td><%= player["turnovers_per_game"].to_f.round(1) %></td>
              <td><%= player["rank_value"].round(2) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </main>
</div>

app/views/players/show.html.erb
<% content_for :head do %>
  <%= javascript_pack_tag 'player' %>
<% end %>
<div id="player_app" class="container">
</div>