config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#custom'

  devise_for :users
  root "players#index"

  get "/search" => "players#search"
  get "/pages/about" => "pages#about"
  get "/teams/schedule" => "teams#schedule"
  get "/players/compare" => "players#compare"

  resources :players, param: :player_id do
    collection do
      post :conditions
    end
  end

  # resources :posts

  # API routes
  namespace :api do
    namespace :v1 do
      get "leagues/index", to: "leagues#index"
      get "leagues/roster", to: "leagues#roster"
      get "players/value/:player_id", to: "players#value"
      get "players/log/:player_id", to: "players#log"
      get "players/info/:player_id", to: "players#info"
      get "players/list", to: "players#list"
      get "players/score/:player_id", to: "players#score"
      get "teams/schedule", to: "teams#schedule"
    end
  end

  resources :leagues
end

app/views/layouts/_header.html.erb
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= image_tag("logo.png", alt: "logp", height:40, weight:40) %>
      <%= link_to "台灣Fantasy大聯盟", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">分析工具</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <%= link_to "Rank排名", root_path, class: "dropdown-item" %>
              <%= link_to "球員比較", players_compare_path, class: "dropdown-item" %>
              <%= link_to "賽程分析", teams_schedule_path, class: "dropdown-item" %>
            </div>
          </li>
          <!-- <li class="nav&#45;item"> -->
          <!--   <%= link_to "討論區", "#", class: "nav&#45;link" %> -->
          <!-- </li> -->
          <li class="nav-item">
            <%= link_to "關於我們", pages_about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "我的聯盟", leagues_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.facebook.com/%E5%8F%B0%E7%81%A3Fantasy%E5%A4%A7%E8%81%AF%E7%9B%9F-106004520979736/" target="_blank" >Facebook</a>
          </li>
          <% if user_signed_in?  %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.user_name %></a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <%= link_to "設定", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "登出", destroy_user_session_path, method: "delete", class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li>
              <%= link_to "登入/註冊", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
      <%= form_tag search_path, :method => "get", class: "form-inline mt-2 mt-md-0" do %>
        <%= search_field_tag :search, params[:api_person_id], placeholder: "球員名稱", class: "form-control mr-sm-2" %>
        <%= button_tag "搜尋", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </div>
  </nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>台灣Fantasy大聯盟</title>
    <meta name="keywords" content="fantasy,basketball,籃球,數據,分析" />
    <meta name="description" content="台灣 fantasy 籃球 數據分析" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-159934038-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-159934038-1');
    </script>
    <%= favicon_link_tag asset_path("logo.png") %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>